server {
    listen 80;
    listen [::]:80;
    server_name autosapience.bonettoconamor.com;

    root /var/www/autosapience;
    index index.html;

    # SPA routing — crítico para React Router / Next.js Export
    location / {
        try_files $uri $uri/ /index.html;
    }
}
